version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules